### ISSUE TITLE
Unknown command: 'sync_waliki'

### ISSUE THREAD

**Issue by ostrokach** [mgaitan/waliki#105]
I can't get `waliki` to run.

Everything goes ok up until the line:

    $ python manage.py sync_waliki

at which point I get an error:

    Unknown command: 'sync_waliki'
    Type 'manage.py help' for usage.

If I run `python manage.py runserver`, I get an error:

    Performing system checks...

    System check identified no issues (0 silenced).
    June 22, 2015 - 21:16:40
    Django version 1.8.2, using settings 'test_waliki.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    Traceback (most recent call last):
      File "/home/username/anaconda/lib/python2.7/wsgiref/handlers.py", line 85, in run
        self.result = application(self.environ, self.start_response)
      File "/home/username/anaconda/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
        return self.application(environ, start_response)
      File "/home/username/anaconda/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
        self.load_middleware()
      File "/home/username/anaconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 50, in load_middleware
        mw_class = import_string(middleware_path)
      File "/home/username/anaconda/lib/python2.7/site-packages/django/utils/module_loading.py", line 24, in import_string
        six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
      File "/home/username/anaconda/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_string
        module_path, class_name = dotted_path.rsplit('.', 1)
    ImportError: waliki doesn't look like a module path
    [22/Jun/2015 21:16:46]"GET / HTTP/1.1" 500 59

And the website says:

    A server error occurred.  Please contact the administrator.

I get the same errors running Python 2.7 and 3.4.

**Comment by mgaitan** [comment]
hey @ostrokach . could your share your complete `settings.py` file?

do you want just a vanilla waliki site or you are integrating it in a pre-existent django project? it the case is the former, may be you can check (or use) the demo project

https://github.com/mgaitan/waliki/tree/master/waliki_project

**Comment by ostrokach** [comment]
I was trying to test waliki out using a vanilla django site. Basically, I just ran

    $ django-admin startproject mysite

and followed the instructions in the waliki README. My `settings.py` file is pasted below, but it's just the default django file with waliki imports. Using the waliki demo project works as expected (after installing `django_allauth` and `django_analytical`), so I'm just playing around with it for now. Thanks :).

    #settings.py
    """
    Django settings for test_waliki project.

    Generated by 'django-admin startproject' using Django 1.8.2.

    For more information on this file, see
    https://docs.djangoproject.com/en/1.8/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/1.8/ref/settings/
    """

    # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
    import os

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'y6sn0u=j#41x1p9jcr4^ai7pos4_r1v%$veatqzhv(%!b93zxv'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = []


    # Application definition

    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    )

    MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'django.middleware.security.SecurityMiddleware',
        'waliki',
        'waliki.git',
        'waliki.attachments',
        'waliki.pdf',
        'waliki.slides',
        'waliki.togetherjs',
    )

    # WALIKI_DATA_DIR = 'waliki_data'

    # WALIKI_ANONYMOUS_USER_PERMISSIONS = ('view_page', 'add_page', 'change_page',)

    ROOT_URLCONF = 'test_waliki.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'test_waliki.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/1.8/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


    # Internationalization
    # https://docs.djangoproject.com/en/1.8/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.8/howto/static-files/

    STATIC_URL = '/static/'

**Comment by mgaitan** [comment]
@ostrokach 



```
TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages",
    "django.core.context_processors.request",
    "waliki.context_processors.settings"
)
```

**Comment by mgaitan** [comment]
@ostrokach sorry, I closed the issue accidentally with a non-sense message.  I would like to debug it, because having a good starting experience is a must for new users. 

Let me know if to define those template context processors helps.

**Comment by ostrokach** [comment]
@mgaitan Really sorry for wasting your time, you can close the issue.

The reason I was getting the errors was because I put 

    'waliki',
    'waliki.git',
    'waliki.attachments',
    'waliki.pdf',
    'waliki.slides',
    'waliki.togetherjs',

into `MIDDLEWARE_CLASSES` rather than `INSTALLED_APPS` (facepalm...).

**Comment by mgaitan** [comment]
ok, cool
