### ISSUE TITLE
Git plugin pages don't show breadcrumbs

### ISSUE THREAD

**Issue by wagnerflo** [mgaitan/waliki#138]
The code to add the `breadcrumbs` variable is used in `waliki.views` but not in the view functions in `waliki.git.views`. So these pages show no breadcrumbs.

Temporarily I've helped myself with a custom template tag for my project. Maybe this would also be the solution to use in general?

**Comment by mgaitan** [comment]
could you share your workaround? thanks for all your contributions, btw
