### ISSUE TITLE
No module named 'waliki.git'

### ISSUE THREAD

**Issue by d-nnis** [mgaitan/waliki#80]
Followed install procedure (https://github.com/mgaitan/waliki/#how-to-start) pip install waliki[all] etc.

Installation and migrate went fine.

Problem occurs on 
Python 3.4.3,
Django==1.7.7 and Django==1.8

**Comment by mgaitan** [comment]
On Fri, Apr 10, 2015 at 8:15 AM, Dennis <notifications@github.com> wrote:

> pip install waliki[all]



thanks for the report, checking it right now because if it's valid, is too
bad!


-- 
mgaitan.github.io
textosypretextos.com.ar <http://textosyprextextos.com.ar>

**Comment by mgaitan** [comment]
@d-nnis hey Dennis, I've just create a new vanilla virtualenv and follow those intructions without major problems. 

I found little ones: the default for `WALIKI_ANONYMOUS_USER_PERMISSIONS` is just `('view_page',)` so, without a way to signup/login, nobody can edit a page. the canonical workaround is to give edit permission to any visitor: 

```
WALIKI_ANONYMOUS_USER_PERMISSIONS = ('view_page', 'add_page', 'change_page')`
```

Also, the css in the "project" (the code that run the demo) is tweaked a bit, and the header looks bad without that touches. 

but no, I hadn't problem to install it. 

Are you using a virtualenv ? Can you paste here the exatly steps you are using and the complete output ? Which is your operating system? 

thanks in advance for helping here and for give a chance to waliki :ok_hand:

**Comment by d-nnis** [comment]
Hey there, thanks for your dedication.

I do use pyenv as virtualenv on 
    Linux acer-nas 3.2.0-77-generic #114-Ubuntu SMP Tue Mar 10 17:25:28 UTC 2015 i686 i686 i386 GNU/Linux

pip-installation with --upgrade deinstalled django==1.7.7 and installed django==1.8
virtualenv has Python 3.4.3 and Django 1.8
Here are the installing logs

    (py343dj177) dennis@acer-nas:~$ pip install waliki[all] --upgrade
    Requirement already up-to-date: waliki[all] in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages
    Requirement already up-to-date: pyquery in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: docutils in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Collecting django (from waliki[all])
    Using cached Django-1.8-py2.py3-none-any.whl
    Requirement already up-to-date: rst2html5==1.6 in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: Markups in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: sh in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: hovercraft in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: django-sendfile in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: micawber in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Requirement already up-to-date: markdown in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from waliki[all])
    Collecting rst2pdf (from waliki[all])
    Using cached rst2pdf-0.93.tar.gz
    Requirement already up-to-date: lxml>=2.1 in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from pyquery->waliki[all])
    Requirement already up-to-date: cssselect in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from pyquery->waliki[all])
    Requirement already up-to-date: Genshi in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from rst2html5==1.6->waliki[all])
    Requirement already up-to-date: Pygments in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from rst2html5==1.6->waliki[all])
    Requirement already up-to-date: svg.path in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from hovercraft->waliki[all])
    Requirement already up-to-date: Unidecode in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from django-sendfile->waliki[all])
    Collecting setuptools (from rst2pdf->waliki[all])
    Downloading setuptools-15.0-py2.py3-none-any.whl (501kB)
        100% |████████████████████████████████| 503kB 294kB/s 
    Requirement already up-to-date: reportlab>=2.4 in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from rst2pdf->waliki[all])
    Requirement already up-to-date: pdfrw in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from rst2pdf->waliki[all])
    Requirement already up-to-date: pillow>=2.4.0 in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from reportlab>=2.4->rst2pdf->waliki[all])
    Requirement already up-to-date: pip>=1.4.1 in ./.pyenv/versions/py343dj177/lib/python3.4/site-packages (from reportlab>=2.4->rst2pdf->waliki[all])
    Installing collected packages: django, setuptools, rst2pdf
    Found existing installation: Django 1.7.7
        Uninstalling Django-1.7.7:
        Successfully uninstalled Django-1.7.7
    Found existing installation: setuptools 12.0.5
        Uninstalling setuptools-12.0.5:
        Successfully uninstalled setuptools-12.0.5
    Found existing installation: rst2pdf 0.93.dev-r0
        Uninstalling rst2pdf-0.93.dev-r0:
        Successfully uninstalled rst2pdf-0.93.dev-r0
    Running setup.py install for rst2pdf
    Successfully installed django-1.8 rst2pdf-0.93.dev-r0 setuptools-15.0
    (py343dj177) dennis@acer-nas:~$ 

Provided the standard settings after django-admin.py startproject waliki i added - according to installing instructions:
    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'waliki',
        'waliki.git',           # optional but recommended
        'waliki.attachments',   # optional but recommended
        'waliki.pdf',           # optional
        'waliki.slides',        # optional
        'waliki.togetherjs',    # optional
    )

Starting the server with manage.py runserver returned this:

    (py343dj177) dennis@acer-nas:/media/NASDRIVESAMSUNG/home/server/djangosite/waliki$ ./manage.py runserver
    Traceback (most recent call last):
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/py343dj177/lib/python3.4/site-packages/django/apps/config.py", line 114, in create
        cls = getattr(mod, cls_name)
    AttributeError: 'module' object has no attribute 'git'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/py343dj177/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/py343dj177/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
        django.setup()
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/py343dj177/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
        apps.populate(settings.INSTALLED_APPS)
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/py343dj177/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
        app_config = AppConfig.create(entry)
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/py343dj177/lib/python3.4/site-packages/django/apps/config.py", line 119, in create
        import_module(entry)
    File "/media/NASDRIVESAMSUNG/home/dennis/.pyenv/versions/3.4.3/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
    File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
    File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
    ImportError: No module named 'waliki.git'
    (py343dj177) dennis@acer-nas:/media/NASDRIVESAMSUNG/home/server/djangosite/waliki$

**Comment by mgaitan** [comment]
hey, dennis, I've just tried used pyenv (instead of virtualenv(wrapper)) and it worked. Now, revising your traceback a bit more carefully, I think the problem it that you named the your django project "waliki". 

As django put the project path in the `PYTHON_PATH` with a high priority, it override the actual `waliki` package. 

So, try something like  `django-admin startproject waliki_test`

**Comment by mgaitan** [comment]
Please, let me know if it worked.

**Comment by d-nnis** [comment]
Hey mgaitan,

after starting the project with another name it did not throw any error message and I could reach the start page (/wiki/). Thanks you very much for your assistance! :-)

Have a nice weekend,
Dennis.

**Comment by mgaitan** [comment]
great!
