### ISSUE TITLE
url for attachaments should use file basename instead of id

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/waliki#96]
otherwise, replacing a file with the a new version with the same name require edit the document to change ids. 

the changes should be **backward compatible**

**Comment by RobertoMaurizzi** [comment]
Hello, I just installed Waliki from git tarball and on python 3 :-)

I tried to copy a "slide page" from Hovercraft! and I run into a few problems with attachment naming: if you have a :css: directives, it needs the actual filename on disk, if instead you refer to an image you can simply attach it and use the :image: command created by the attachment manager.

IMHO the only decent solution is to use the same relative path for both the web and the filesystem and avoid the id component: if a user re-saves another file with the same name, it'll be overwritten and eventually it can be recovered from git's repo.

Having the same relative paths is also in the interest of reusing the .rst documents "alone" without waliki (I had a tiny but useful wiki in Zope and I'll never use something else that can't allow me easy replication and independent access to my files ;-) )

**Comment by mgaitan** [comment]
Hello @RobertoMaurizzi, I completely agree with your arguments.  I have a branch started but a bit outdated
https://github.com/mgaitan/waliki/compare/96_attachment_no_id

I would like to have this for the next version, but my daughter was born few days ago and my "open source time" decreased a lot for obvious reasons :baby_bottle: 

do you feel confident to continue/redone that ?
